// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rgmgimpdrlqxnimolilx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnbWdpbXBkcmxxeG5pbW9saWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NTAzMzksImV4cCI6MjA0ODAyNjMzOX0.1wHB68KPfuU3Aaa7lxGmcygT-BpdeNheXmzmGQVXJuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);